ifndef::imagesdir[:imagesdir: ../images]

== Einführung und Ziele

=== Aufgabenstellung

Die link:https://vitamineb.ch/digital/[heutige Landschaft von eingesetzten digitalen Tools] zur Organisation von Vereinen und anderen Non-Profit-Organisationen ist stark geprägt von proprietären Software-Lösungen, welche nur ein geringes Mass an s.g. link:https://www.cio.bund.de/Webs/CIO/DE/digitale-loesungen/digitale-souveraenitaet/digitale-souveraenitaet-node.html[digitaler Souveränität] mit sich bringen. Dies führt zu einer starken Abhängigkeit zwischen Nutzenden und Anbietern auch bekannt als link:https://de.wikipedia.org/wiki/Lock-in-Effekt["Vendor bzw. Produkt Lock-In"].

Wir wollen im Rahmen eines Innovationsschecks prüfen, ob 
 1. In den NPOs bereits eine Sensibilisierung für das Thema vorliegt
 2. Wo Bedarf an digitalen Lösungen und Anbindungen besteht und welche Software zum Einsatz kommt
 3. Es für den Bedarf in den jeweiligen Teilbereichen (Kommunizieren und Arbeiten, Dokumente & Datenablage, Projektmanagement, ...) offene (s.g. open source) Lösungen gibt, welche als Alternativen angeführt bzw. empfohlen werden können

Ziel ist es die Souveränität von link:https://www.deutsche-stiftung-engagement-und-ehrenamt.de/opensource-tools/[ehrenamtlichen Organisationen in Bezug auf Digitalisierung] zu unterstützen und zu stärken.

=== Qualitätsziele

Aufgrund der Fokussierung auf die "Digitale Souveräntität" wurden folgende drei Qualitätseigenschaften nach Q42 festgehalten.

[%header,cols="1,1"]
|===
| link:https://quality.arc42.org[Q42 Eigenschaft]
| link:https://quality.arc42.org/properties/[Qualität]

| link:https://quality.arc42.org/tag-suitable/[#suitable]
| link:https://quality.arc42.org/qualities/functional-appropriateness[functional appropriateness]

.3+| link:https://quality.arc42.org/tag-operable/[#operable]
| link:https://quality.arc42.org/qualities/autonomy[autonomy]

| link:https://quality.arc42.org/qualities/releasability[releasability]

| link:https://quality.arc42.org/qualities/deployability[deployability]

| link:https://quality.arc42.org/tag-flexible/[#flexible]
| link:https://quality.arc42.org/qualities/maintainability[maintainability]

|===

=== Stakeholder

[role="arc42help"]
****
.Inhalt
Expliziter Überblick über die Stakeholder des Systems – über alle Personen, Rollen oder Organisationen –, die

* die Architektur kennen sollten oder
* von der Architektur überzeugt werden müssen,
* mit der Architektur oder dem Code arbeiten (z.B. Schnittstellen nutzen),
* die Dokumentation der Architektur für ihre eigene Arbeit benötigen,
* Entscheidungen über das System und dessen Entwicklung treffen.

.Motivation
Sie sollten die Projektbeteiligten und -betroffenen kennen, sonst erleben Sie später im Entwicklungsprozess Überraschungen.
Diese Stakeholder bestimmen unter anderem Umfang und Detaillierungsgrad der von Ihnen zu leistenden Arbeit und Ergebnisse.

.Form
Tabelle mit Rollen- oder Personennamen, sowie deren Erwartungshaltung bezüglich der Architektur und deren Dokumentation.
****

[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| _<Rolle-1>_ | _<Kontakt-1>_ | _<Erwartung-1>_
| _<Rolle-2>_ | _<Kontakt-2>_ | _<Erwartung-2>_ 
|===
