ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== Randbedingungen

=== Umfrage in der Schweiz zum Thema "Digitale Souveränität von Vereinen"

Zwischen Q2 und Q3 2024 haben wir im Rahmen dieser Studie zufällig ausgewählte schweizer Vereine angeschrieben und um die Teilnahme an der Umfrage gebeten. Insgesamt haben 167 Vereine teilgenommen, 81 haben vollständig im Rahmen der Umfrage auf unseren Fragen geantwortet.

==== Selbsteinschätzung zur Verbreitung und Anwendung

===== Bekanntheitsgrad

____
Das Konzept "Digitale Souveränität" ist bei unserem Verein bekannt:
____

[source,shell]
----
include::02/Q0102-1.output[]
---
1 : Trifft gar nicht zu
10: Trifft vollständig zu
----

===== Relevantheitsgrad

____
Das Konzept "Digitale Souveränität" wird bei unserem Verein als relevant eingestuft:
____

[source,shell]
----
include::02/Q0102-2.output[]
---
1 : Trifft gar nicht zu
10: Trifft vollständig zu
----

===== Im Alltag gelebt

____
Das Konzept "Digitale Souveränität" wird bei unserem Verein im Alltag gelebt:
____

[source,shell]
----
include::02/Q0102-3.output[]
---
1 : Trifft gar nicht zu
10: Trifft vollständig zu
----

===== Empfehlungen bekannt?

----
Nutzen Sie bereits Empfehlungen wie bspw. der Fachstelle für Vereine (vitaminB) oder der Deutschen Stiftung für Engagement und Ehrenamt (DSEE)?
----

[source,shell]
----
include::02/Q0103.output[]
----

==== Selbstauskunft zum Grad der "Digitalisierung"

----
Selbstauskunft zum Grad der "Digitalisierung": Bitte jeden Teilbereich ankreuzen, wenn ein digitaler Prozess existiert und als Kommentar die Software / die Tools die zum Einsatz kommt bzw. kommen.
----

[source,shell]
----
include::02/Q0104-1.output[]
----

===== Tools im Bereich "Kommunizieren"

[source,shell]
----
include::02/Q0104-2.output[]
----

===== Tools im Bereich "Arbeiten planen"

[source,shell]
----
include::02/Q0104-3.output[]
----

===== Tools im Bereich "Vereinsaktivitaeten organisieren"

[source,shell]
----
include::02/Q0104-4.output[]
----

===== Tools im Bereich "Termine planen"

[source,shell]
----
include::02/Q0104-5.output[]
----

===== Tools im Bereich "Dokumente gemeinsam bearbeiten"

[source,shell]
----
include::02/Q0104-6.output[]
----

===== Tools im Bereich "Vereinssoftware"

[source,shell]
----
include::02/Q0104-7.output[]
----

===== Tools im Bereich "Clouds Datenablage"

[source,shell]
----
include::02/Q0104-8.output[]
----

===== Tools im Bereich "Projektmanagement"

[source,shell]
----
include::02/Q0104-9.output[]
----

===== Tools im Bereich "Quiz Umfragen Abstimmungen"

[source,shell]
----
include::02/Q0104-10.output[]
----

===== Tools im Bereich "Ideen Sammeln Kreativ gestalten"

[source,shell]
----
include::02/Q0104-11.output[]
----

===== Tools im Bereich "Videos Designs und Podcasts kreieren"

[source,shell]
----
include::02/Q0104-12.output[]
----

===== Tools im Bereich "Video Konferenzen Online Meetings"

[source,shell]
----
include::02/Q0104-13.output[]
----

===== Tools im Bereich "Websites Video Tutorials Unterlagen"

[source,shell]
----
include::02/Q0104-14.output[]
----

==== Einschätzung (digitale) Prozesse & Software-Tools - mit grossem Impact

===== in der internen Vereinsorganisation

----
Welche (digitalen) Tools haben bei Ihnen in der internen Vereinsorganisation grossen Impact (und warum)?
----

[source,shell]
----
include::02/Q0201.output[]
----

===== im Vereinsleben

----
Welche (digitalen) Tools haben bei Ihnen im Vereinsleben grossen Impact (und warum)?
----

[source,shell]
----
include::02/Q0202.output[]
----

==== Einschätzung (digitale) Prozesse & Software-Tools - mit grossem Handlungsbedarf

----
Wo besteht grosser Handlungsbedarf an einem (digitalen, automatisierten) Prozess bzw. Software?
----

----
Wo besteht grosser Handlungsbedarf einer besseren Integration von bestehenden Tools?
----

Beide Fragestellungen haben ein sehr heterogenes Antwortenbild ohne klare Tendenzen aufgezeigt, einziger Trend hier ist, dass die meisten keinen akuten Handlungsbedarf benennen bzw. benennen können. 

=== Studien und Referenzen

==== Empfehlungen der Fachstelle für Vereine "vitamin B"

Liste an Tools für die (digitale) Zusammenarbeit: https://vitamineb.ch/digital/

==== Empfehlungen der Deutschen Stiftung for Engagement und Ehrenamt

https://www.deutsche-stiftung-engagement-und-ehrenamt.de/opensource-tools/

==== fundraiser-magazin.de - Software für Vereine, Verbände und Stiftungen im Vergleich – die Marktübersicht 2024

https://web.fundraiser-magazin.de/software-marktuebersicht-vereine-verbaende-stiftungen

==== Komponenten der digital souveränen Arbeitsplatzlösung openDesk

https://gitlab.opencode.de/bmi/opendesk/info/-/blob/main/OVERVIEW.md#komponenten-von-opendesk

==== Studien zu Open-Source-Alternativen von Microsoft Services und Produkten in der Schweizerischen Bundesverwaltung

Studie zu Open-Source-Alternativen von Microsoft Services und Produkten in der Schweizerischen Bundesverwaltung link:https://www.bk.admin.ch/dam/bk/de/dokumente/dti/themen/CEBA/studie-zu-open-source-alternativen-von-microsoft-services-und-produkten-in-der-schweizerischen-bundesverwaltung-frontend-services.pdf.download.pdf[Frontend-Services].

Studie zu Open-Source-Alternativen von Microsoft Services und Produkten in der Schweizerischen Bundesverwaltung link:https://www.bk.admin.ch/dam/bk/de/dokumente/dti/themen/CEBA/studie-zu-open-source-alternativen-von-microsoft-services-und-produkten-in-der-schweizerischen-bundesverwaltung-backend-services.pdf.download.pdf[Backend-Services].